import "bootstrap/dist/css/bootstrap.min.css";
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ContentIndex from "../Component/index.js";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sofrware Programmer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      </Head>
      <ContentIndex />

      <footer className="mt-5">
        <a
          href="https://www.nurchy.com/"
          target="_blank"
          rel="noopener noreferrer"
          style={{textDecoration: 'none'}}
        >
          Powered by{' '}
          <span>
            Nur Cahyo Prasetiyo
          </span>
        </a>
      </footer>
    </div>
  )
}
